server:
  dev_mode: true 
  port: 8080
  max_upload: 1024 # Mb (1GB Default limit)
  domain: "example.com"

paths:
  public: "./public"
  uploads: "./uploads"

auth:
  token: "your-secret-token"

logging:
  discord:
    enabled: true
    webhook_url: "https://discord.com/webhookUrl" # Optional if disabled
