server:
  devMode: true 
  port: "8080"
  domain: "example.com"

paths:
  public: "./public"
  uploads: "./uploads"

auth:
  token: "your-secret-token"

logging:
  discord:
    enabled: true
    webhook_url: "https://discord.com/webhookUrl"
