# version: '3.8'

services:
  file-server:
    build: ./
    ports:
      - "8080:8080"
    volumes:
      - ./public:/file-server/public
      - file-server-uploads:/file-server/uploads
      - ./config.yaml:/file-server/config.yaml


volumes:
  proxy-data-volume:
  file-server-uploads:
