services:
  neoserve:
    build: ./
    image: neoserve:latest
    ports:
      - "8080"
    volumes:
      - ./public:/opt/neoserve/public
      - neoserve-uploads:/opt/neoserve/uploads
      - ./config.yaml:/opt/neoserve/config.yaml


volumes:
  neoserve-uploads:
