name: Build Project

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup Go Env
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Build Go Binary
      run: |
        mkdir -p build/public
        mkdir -p build/uploads
        echo "Copying example config file to build folder"
        cp config.example.yaml build/config.example.yaml

        echo "Copying web files to build folder"
        cp public/* build/public/
        cp uploads/* build/uploads/

        echo "Building go project"
        go build -v -o build/neoserve

    - name: Create Release Tag
      if: github.ref == 'refs/heads/main'
      run: |
        VERSION="v1.0.0"
        git tag -a "$VERSION" -m "🚀 Artefact Release $VERSION"
        git push origin "$VERSION"

    - name: Upload Build Binary
      if: github.ref == 'refs/heads/main'
      uses: actions/upload-artifact@v4
      with:
        name: build-artifact  # Specify a name for the artifact
        path: ./build/**  # Specify the path to the build output (e.g., ./bin/your-app)
        retention-days: 30  # Optional: Set retention period for the artifact
